### ISSUE TITLE
add an optional email address support to class roster

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/classes#12]
The email address parameter has been updated to the user/setup api. If provided, it will be used instead of the requester's email address.

**Comment by jeroen** [comment]
What exactly is this paramter called? Can you update the documentation? https://github.com/ohmage/server/wiki/User-Manipulation#userSetup

**Comment by jeroen** [comment]
Fixed @ https://github.com/mobilizingcs/classes/commit/fa0e7cbd5dd16372b3d095273b1b7064ee8a4aa9.
