### ISSUE TITLE
campaign list in class subrow

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/classes#18]
so users who cannot manage classes can still see:
- priv user list
- restricted user list
- campaign list

**Comment by jeroen** [comment]
This is not exactly trivial. The `/class/read` api only returns a list of users. So we would have to do a `campaign/read` to list all campaigns and then for a given class, search through the campaign data to find the campaigns that are associated with this class.

**Comment by jeroen** [comment]
https://github.com/mobilizingcs/classes/commit/c72a7367a81fd8ddbd128771970d8c85a8a6a387
