### ISSUE TITLE
count summary

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/classes#21]
Can we add a total # of count for campaigns and users next to section header e.g. Campaigns (6)? 
This way, it won't change the current layout and I can get the summary at the same time.

**Comment by jeroen** [comment]
Done @ https://github.com/mobilizingcs/classes/commit/513d380166794123e6f6d43944fe61d35920ba2d

**Comment by jeroen** [comment]
Wait did you mean in the campaign list overview, or the edit campaign page?
