### ISSUE TITLE
odd message with csv with lausd format

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/classes#25]
Is this something that can easily be accounted for?

<img width="1217" alt="screen shot 2016-02-05 at 10 54 07 am" src="https://cloud.githubusercontent.com/assets/808870/12855919/13422b48-cbf7-11e5-9f9a-2c52269f79cd.png">

http://web.ohmage.org/~snolen/sample_classes/01sample_class.csv

**Comment by jeroen** [comment]
Fixed @ https://github.com/mobilizingcs/classes/commit/61647a20de81f5e1ff6aea2574f97470e38464e2. It still doesn't support the strange lausd import format, but you should see a sensible error message now.

**Comment by stevenolen** [comment]
sounds good. I'm going to see if they have any new methods of exporting rosters now with misis since it's been over a year since launch.  That file is definitely not a csv..
