### ISSUE TITLE
Supporting lausd 'csv' import data

### ISSUE THREAD

**Issue by jeroen** [mobilizingcs/classes#27]
It would be nice if the class manager would support lausd csv import data so that we have one less tool to maintain. However unfortunately lausd has multiple data formats and each of them is non standard. Currently the teacher tool uses the following logic:

``` js
if(rec["StudentCode"]){
    rec.id = rec["StudentCode"]
    rec.firstname = rec["StudentName1"].split(",")[1].trim();
    rec.lastname = rec["StudentName1"].split(",")[0].trim();
} else if(rec["Student ID"]){
    rec.id = rec["Student ID"];
    rec.firstname = rec["Student Name"].split(",")[1].trim();
    rec.lastname = rec["Student Name"].split(",")[0].trim();
} else if(rec["students_id"]){
    rec.id = rec["students_id"];
    rec.firstname = rec["students_firstname"].trim();
    rec.lastname = rec["students_lastname"].trim();
}
```

So we could check for the presence of one of the magic field named `"StudentCode"`, `"Student ID"` or `"students_id"` and based on that assumes a particular format. Do we still need to support each of these 3 lausd formats?

**Comment by jeroen** [comment]
I have added basic support for the lausd format. @stevenolen can you tell me which of the lausd csv formats above we still need to support?

**Comment by stevenolen** [comment]
Works great.  LAUSD only has the one format now, teachers no longer have access to the system that created the older format(s).

I like this too since it doesn't seem too difficult to modify the code in order to support some other district's wild csv format in the future too!
