### ISSUE TITLE
use hashes for class navigation instead of query params

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/classes#3]
when I reload the page while in a class detail, i'm taken back to the class list page.

**Comment by stevenolen** [comment]
not sure if this related to the hash thing or not, but I noticed them both together :)

**Comment by jeroen** [comment]
Fixed this in the navbar: https://github.com/mobilizingcs/navbar/commit/ea4056cf4232c3719bc99e94681eb4d6405f32d5.

**Comment by stevenolen** [comment]
boo! also use a hash instead of the query params though! query params are for server-side parameter management, not really for tracking data from one page to another for a client. unless for some reason you need to use query params here?

**Comment by jeroen** [comment]
Meh

**Comment by jeroen** [comment]
Ah what do i care https://github.com/mobilizingcs/classes/commit/8b911b05ffdeff79320af0de18aee5acdd1552f8

**Comment by stevenolen** [comment]
:sparkles: :tophat: thank you @jeroenooms
