### ISSUE TITLE
Fields 

### ISSUE THREAD

**Issue by jeroen** [mobilizingcs/classes#30]
HT thinks its better to put the school name, curriculum, and subject/period back in the URN.

**Comment by hongsudt** [comment]
I meant whatever we use in the lausd naming convention! I am not sure about
school, but definitely the subject/period..

**Comment by jeroen** [comment]
I overhauled the create class dialog box to support both the lausd conventions as well as an additional free form subject. @stevenolen could you try to test this? https://test.mobilizingcs.org/#classes/

**Comment by stevenolen** [comment]
works really well! Could the modal actually start with _just_ the first dropdown, and then others are shown/hidden based on the answer to the first question? It feels like odd UX to have the lausd subject suggestions appear immediately and then if you select "other/demo" they disappear!

**Comment by jeroen** [comment]
ok @stevenolen I have updated this, can you try if it is now more intuitive?

**Comment by stevenolen** [comment]
:+1:
