### ISSUE TITLE
class/delete optin/optout

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/classes#4]
OPT-OUT

These campaigns are associated only with this class. Please un-check if you'd like to keep the campaigns and responses for use at a later time:

[] Campaign One (checked by default)
[] Campaign Two (checked by default)

[Delete]
# 

OPT-IN

This campaigns are associated only with this class. Please delete these campaigns if you do not wish to save the campaigns and responses for later.

Campaign One [Delete]
Campaign Two [Delete]

[Delete]

**Comment by stevenolen** [comment]
opt-in is general use case, opt-out is "education" ("mobilize") use case.

**Comment by jeroen** [comment]
HT: 

I fixed the server bug that left the user-campaign relationship in tact even after the class is deleted... I also added no_orphan_campaigns flag to class/delete. If it is true, an error will be thrown when you try to delete a class that lead to orphan campaigns.. A list of orphan campaigns will be provided in the error message as well.. By default, this is set to false. 

my idea is that we can use this to support 2 scenarios: 
when the delete button is clicked, call class/delete with no_orphan_campaigns=true.  Then we have 2 options
1. confirm that they want to continue anyway. If so, make the second class/delete without the flag (general case?) 
2. always enforce no orphan campaigns by asking users to delete those orphan campaigns first (Mobilize?)

S:

I think it's fine to consider this a bug if it was never an intended to happen, but we should look into the best way to handle the breaking of this user/campaign relationship for historical cases: what do we do with all of these users that have a direct campaign relationship but no class (eg. they were removed from a class before this bugfix)? Also, what if I've used ohmage and assume, as it always has been, that users will always have access to their own data? Breaking this relationship removes the ability for the user to see data they've shared to a campaign after being removed from a class?

H: 

Yes. This has always been the case. It was intentionally designed this way (focusing more on the researcher's needs)..  If we want the users to see their data, then don't delete them from the class..

**Comment by jeroen** [comment]
I don't quite understand the case for `no_orphan_campaigns=false`. Aren't we trying to prevent orphan campaigns?

**Comment by stevenolen** [comment]
yes, but with `no_orphan_campaigns=false` as default we preserve backwards compatibility with the existing functionality (which was to allow orphan campaigns). We'd like to prevent them with this tool and tools we maintain, but also need to make sure that this new "feature" doesn't change functionality for someone using a different tool to manage their classes.

**Comment by jeroen** [comment]
Okay I get that, but HT proposes:

> confirm that they want to continue anyway. If so, make the second class/delete without the flag

I don't see why we would support that in the new tool.

**Comment by stevenolen** [comment]
oh. I think I'm misunderstanding. @hongsudt ?

**Comment by jeroen** [comment]
It works now like this. If you try to delete the class but there are still campaigns with no other class, it shows an error message and highlights the corresponding campaigns.

**Comment by hongsudt** [comment]
The current design address this problem pretty well. So I am closing this issue.
