### ISSUE TITLE
delete campaign button: confirm before deletion

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/classes#8]
Can you confirm whether they really want to delete a campaign?

**Comment by jeroen** [comment]
It already does that if the campaign has more than 0 responses in it.

**Comment by jeroen** [comment]
That was a requirement in the teacher tool. Do you want to change it to _always_ ask for confirmation?

**Comment by hongsudt** [comment]
Yeap..

They could accidentally delete a campaign that is difficult to recreate..
So lets be safe..
