### ISSUE TITLE
user deletion: need confirmation

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/classes#9]
Should we ask the user to confirm before they delete a user?

**Comment by hongsudt** [comment]
At the very least, we should definitely confirm if the user want to remove herself from the roster? Since after they do so, they won't be able to do anything on that page anymore..

**Comment by jeroen** [comment]
Do note that the class manager does not _delete_ the user, it merely removes it from the class. That's not the same thing.

**Comment by jeroen** [comment]
Added a confirmation.
